import type { ClausesOutput, GraphOutput } from "./schemas";

export const STUDY_QUESTION_IDS = [
  "djorkaeff-inter-fulham",
  "olajuwon-mvp-drexler",
  "theodore-hart-therrien",
  "kubica-gp-theissen",
  "bossy-rookie-selanne",
  "barrichello-wdc-brackley",
  "boli-marseille-goethals",
  "horry-mvp-tomjanovich",
  "savicevic-milan-baresi",
  "kubica-bmw-reithofer",
  "rivera-yankees-brooklyn",
  "hamilton-mercedes-vienna",
  "tortorella-tampa-iginla",
  "olajuwon-draft-williams",
  "brady-patriots-nashville",
  "erving-sixers-brooklyn",
  "giguere-ducks-oilers",
  "billups-pistons-united-states",
  "bryant-lakers-celtics-massachusetts",
  "messi-barca-khaldoon-abu-dhabi",
  "kalou-chelsea-toennies-group",
  "barrichello-brawn-zetsche-daimler",
  "curry-warriors-popovich-east-chicago",
  "cannavaro-juventus-perez-madrid",
] as const;

export type StudyQuestionId = (typeof STUDY_QUESTION_IDS)[number];

export type HopCount = 3 | 4 | 6;

export type StudyQuestionFixture = {
  id: StudyQuestionId;
  studyNumber: string;
  canonicalQuestion: string;
  expectedAnswer: string;
  pathLength: number;
  hopCount: HopCount;
  isCorrect: boolean;
  clauses: ClausesOutput;
  graph: GraphOutput;
  reasoning?: string;
};

export const STUDY_QUESTION_NUMBERS: Record<StudyQuestionId, string> =
  Object.fromEntries(
    STUDY_QUESTION_IDS.map((id, i) => [id, String(i + 1).padStart(2, "0")])
  ) as Record<StudyQuestionId, string>;

export function getStudyNumber(id: StudyQuestionId): string {
  return STUDY_QUESTION_NUMBERS[id];
}

export function sampleStudyQuestions(): StudyQuestionFixture[] {
  return pickN(Object.values(STUDY_QUESTION_FIXTURES), 12);
}

function pickN<T>(pool: T[], n: number): T[] {
  const copy = [...pool];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, n);
}

const scoredTriple = (
  node1: string,
  relationship: string,
  node2: string,
  score: number
) => ({
  node1,
  relationship,
  node2,
  score,
});

const STUDY_QUESTION_FIXTURES_RAW: Record<
  StudyQuestionId,
  Omit<StudyQuestionFixture, "studyNumber">
> = {
  "djorkaeff-inter-fulham": {
    id: "djorkaeff-inter-fulham",
    canonicalQuestion:
      "Which Premier League club did the manager of the team Youri Djorkaeff joined in 1996 later lead?",
    expectedAnswer: "Fulham",
    pathLength: 3,
    hopCount: 3,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "Youri Djorkaeff",
          relationship: "joined",
          node2: "Inter Milan",
        },
        {
          node1: "Inter Milan",
          relationship: "led_by",
          node2: "Roy Hodgson",
        },
        {
          node1: "Roy Hodgson",
          relationship: "led",
          node2: "Fulham",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Youri Djorkaeff", "joined", "Inter Milan", 1.0),
        scoredTriple("Inter Milan", "led_by", "Roy Hodgson", 1.0),
        scoredTriple("Roy Hodgson", "led", "Fulham", 1.0),
        scoredTriple("Roy Hodgson", "led", "Blackburn Rovers", 0.84),
        scoredTriple("Roy Hodgson", "led", "Liverpool", 0.76),
        scoredTriple("Roy Hodgson", "led", "Halmstad BK", 0.68),
        scoredTriple("Roy Hodgson", "led", "England national team", 0.72),
        scoredTriple("Roy Hodgson", "succeeded", "Rafael Benitez", 0.62),
        scoredTriple("Roy Hodgson", "preceded", "Luigi Simoni", 0.55),
        scoredTriple("Roy Hodgson", "belonged_to", "English football managers", 0.51),
        scoredTriple("Youri Djorkaeff", "played_for", "France national team", 0.86),
        scoredTriple("Youri Djorkaeff", "won", "1998 FIFA World Cup", 0.82),
        scoredTriple("Youri Djorkaeff", "played_for", "PSG", 0.71),
        scoredTriple("Youri Djorkaeff", "moved_to", "Bolton Wanderers", 0.58),
        scoredTriple("Inter Milan", "is_in", "Milan", 0.82),
        scoredTriple("Inter Milan", "belonged_to", "Serie A", 0.88),
        scoredTriple("Inter Milan", "used", "San Siro", 0.74),
        scoredTriple("Inter Milan", "had_player", "Javier Zanetti", 0.69),
        scoredTriple("Inter Milan", "won", "1998 UEFA Cup", 0.64),
        scoredTriple("France national team", "won", "1998 FIFA World Cup", 0.78),
        scoredTriple("Rafael Benitez", "led", "Inter Milan", 0.49),
        scoredTriple("Luigi Simoni", "led", "Inter Milan", 0.52),
        scoredTriple("Halmstad BK", "is_in", "Sweden", 0.57),
        scoredTriple("San Siro", "is_in", "Milan", 0.72),
        scoredTriple("Blackburn Rovers", "belonged_to", "Premier League", 0.64),
        scoredTriple("Fulham", "belonged_to", "Premier League", 0.66),
        scoredTriple("Fulham", "is_in", "London", 0.72),
        scoredTriple("Fulham", "used", "Craven Cottage", 0.7),
        scoredTriple("Fulham", "had_player", "Clint Dempsey", 0.64),
        scoredTriple("Liverpool", "belonged_to", "Premier League", 0.67),
        scoredTriple("Javier Zanetti", "led", "Inter Milan", 0.66),
        scoredTriple("PSG", "belonged_to", "Ligue 1", 0.61),
        scoredTriple("Serie A", "contained", "Inter Milan", 0.7),
        scoredTriple("Craven Cottage", "is_in", "London", 0.68),
        scoredTriple("Clint Dempsey", "played_for", "Fulham", 0.62),
      ],
    },
  },
  "olajuwon-mvp-drexler": {
    id: "olajuwon-mvp-drexler",
    canonicalQuestion:
      "Which Basketball Hall of Famer attended the same college as the winner of the 1994 NBA Finals MVP?",
    expectedAnswer: "Clyde Drexler",
    pathLength: 3,
    hopCount: 3,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "1994 NBA Finals MVP",
          relationship: "won_by",
          node2: "Hakeem Olajuwon",
        },
        {
          node1: "Hakeem Olajuwon",
          relationship: "played_for",
          node2: "University of Houston",
        },
        {
          node1: "University of Houston",
          relationship: "produced",
          node2: "Clyde Drexler",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("1994 NBA Finals MVP", "won_by", "Hakeem Olajuwon", 1.0),
        scoredTriple("Hakeem Olajuwon", "played_for", "University of Houston", 1.0),
        scoredTriple("University of Houston", "produced", "Clyde Drexler", 1.0),
        scoredTriple("University of Houston", "is_in", "Houston", 0.82),
        scoredTriple("University of Houston", "belonged_to", "NCAA", 0.85),
        scoredTriple("University of Houston", "contained", "Phi Slama Jama", 0.78),
        scoredTriple("University of Houston", "led_by", "Guy Lewis", 0.68),
        scoredTriple("University of Houston", "played_in", "1983 NCAA Championship", 0.72),
        scoredTriple("University of Houston", "belonged_to", "American Athletic Conference", 0.61),
        scoredTriple("University of Houston", "used", "Fertitta Center", 0.56),
        scoredTriple("Hakeem Olajuwon", "played_for", "Houston Rockets", 0.88),
        scoredTriple("Hakeem Olajuwon", "won", "1994 NBA Championship", 0.84),
        scoredTriple("Hakeem Olajuwon", "won", "1995 NBA Championship", 0.79),
        scoredTriple("Hakeem Olajuwon", "belonged_to", "NBA", 0.86),
        scoredTriple("Hakeem Olajuwon", "born_in", "Lagos", 0.62),
        scoredTriple("Hakeem Olajuwon", "won", "1994 NBA MVP", 0.76),
        scoredTriple("Clyde Drexler", "played_for", "Houston Rockets", 0.78),
        scoredTriple("Clyde Drexler", "played_for", "Portland Trail Blazers", 0.74),
        scoredTriple("Clyde Drexler", "coached", "University of Houston", 0.6),
        scoredTriple("Clyde Drexler", "won", "1992 NBA Finals", 0.64),
        scoredTriple("Houston Rockets", "belonged_to", "NBA", 0.82),
        scoredTriple("Houston Rockets", "had_player", "Hakeem Olajuwon", 0.86),
        scoredTriple("Houston Rockets", "used", "The Summit", 0.58),
        scoredTriple("Phi Slama Jama", "had_player", "Hakeem Olajuwon", 0.72),
        scoredTriple("Phi Slama Jama", "had_player", "Clyde Drexler", 0.74),
        scoredTriple("Guy Lewis", "led", "Phi Slama Jama", 0.65),
        scoredTriple("1983 NCAA Championship", "won_by", "NC State", 0.58),
        scoredTriple("NC State", "led_by", "Jim Valvano", 0.54),
        scoredTriple("Jim Valvano", "founded", "V Foundation", 0.48),
        scoredTriple("Lagos", "is_in", "Nigeria", 0.67),
        scoredTriple("1994 NBA Championship", "won_by", "Houston Rockets", 0.75),
        scoredTriple("NBA", "contained", "Houston Rockets", 0.6),
        scoredTriple("NCAA", "contained", "University of Houston", 0.58),
      ],
    },
  },
  "theodore-hart-therrien": {
    id: "theodore-hart-therrien",
    canonicalQuestion:
      "Who coached the team that employed the player who won the 2002 NHL Hart Trophy?",
    expectedAnswer: "Michel Therrien",
    pathLength: 3,
    hopCount: 3,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2002 NHL Hart Trophy",
          relationship: "won_by",
          node2: "Jose Theodore",
        },
        {
          node1: "Jose Theodore",
          relationship: "played_for",
          node2: "Montreal Canadiens",
        },
        {
          node1: "Montreal Canadiens",
          relationship: "coached_by",
          node2: "Michel Therrien",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2002 NHL Hart Trophy", "won_by", "Jose Theodore", 1.0),
        scoredTriple("Jose Theodore", "played_for", "Montreal Canadiens", 1.0),
        scoredTriple("Montreal Canadiens", "coached_by", "Michel Therrien", 1.0),
        scoredTriple("Michel Therrien", "led", "Pittsburgh Penguins", 0.82),
        scoredTriple("Michel Therrien", "belonged_to", "NHL coaches", 0.72),
        scoredTriple("Michel Therrien", "preceded", "Claude Julien", 0.68),
        scoredTriple("Michel Therrien", "born_in", "Montreal", 0.58),
        scoredTriple("Michel Therrien", "succeeded", "Alain Vigneault", 0.62),
        scoredTriple("Michel Therrien", "coached_in", "QMJHL", 0.54),
        scoredTriple("Michel Therrien", "developed", "Sidney Crosby", 0.56),
        scoredTriple("Jose Theodore", "played_for", "Colorado Avalanche", 0.74),
        scoredTriple("Jose Theodore", "won", "Vezina Trophy", 0.78),
        scoredTriple("Jose Theodore", "born_in", "Laval", 0.55),
        scoredTriple("Jose Theodore", "belonged_to", "NHL", 0.8),
        scoredTriple("Montreal Canadiens", "is_in", "Montreal", 0.86),
        scoredTriple("Montreal Canadiens", "used", "Bell Centre", 0.82),
        scoredTriple("Montreal Canadiens", "belonged_to", "NHL", 0.84),
        scoredTriple("Montreal Canadiens", "won", "1993 Stanley Cup", 0.7),
        scoredTriple("Montreal Canadiens", "had_player", "Saku Koivu", 0.66),
        scoredTriple("Claude Julien", "coached", "Montreal Canadiens", 0.64),
        scoredTriple("Claude Julien", "coached", "Boston Bruins", 0.62),
        scoredTriple("Pittsburgh Penguins", "belonged_to", "NHL", 0.72),
        scoredTriple("Pittsburgh Penguins", "had_player", "Sidney Crosby", 0.78),
        scoredTriple("Sidney Crosby", "won", "Hart Trophy", 0.74),
        scoredTriple("Colorado Avalanche", "belonged_to", "NHL", 0.68),
        scoredTriple("Colorado Avalanche", "is_in", "Denver", 0.64),
        scoredTriple("Bell Centre", "is_in", "Montreal", 0.76),
        scoredTriple("Saku Koivu", "captained", "Montreal Canadiens", 0.6),
        scoredTriple("Vezina Trophy", "belonged_to", "NHL Awards", 0.62),
        scoredTriple("Hart Trophy", "belonged_to", "NHL Awards", 0.64),
        scoredTriple("2002 NHL Hart Trophy", "belonged_to", "NHL Awards", 0.7),
        scoredTriple("Boston Bruins", "belonged_to", "NHL", 0.66),
        scoredTriple("Laval", "is_in", "Quebec", 0.52),
      ],
    },
  },
  "kubica-gp-theissen": {
    id: "kubica-gp-theissen",
    canonicalQuestion:
      "Who was the team principal of the constructor that employed the driver who won the 2008 Canadian Grand Prix?",
    expectedAnswer: "Mario Theissen",
    pathLength: 3,
    hopCount: 3,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2008 Canadian Grand Prix",
          relationship: "won_by",
          node2: "Robert Kubica",
        },
        {
          node1: "Robert Kubica",
          relationship: "drove_for",
          node2: "BMW Sauber",
        },
        {
          node1: "BMW Sauber",
          relationship: "led_by",
          node2: "Mario Theissen",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2008 Canadian Grand Prix", "won_by", "Robert Kubica", 1.0),
        scoredTriple("Robert Kubica", "drove_for", "BMW Sauber", 1.0),
        scoredTriple("BMW Sauber", "led_by", "Mario Theissen", 1.0),
        scoredTriple("Mario Theissen", "worked_for", "BMW", 0.84),
        scoredTriple("Mario Theissen", "led", "BMW Motorsport", 0.78),
        scoredTriple("Mario Theissen", "succeeded", "Gerhard Berger", 0.62),
        scoredTriple("Mario Theissen", "studied_at", "RWTH Aachen", 0.54),
        scoredTriple("Mario Theissen", "born_in", "Munich", 0.58),
        scoredTriple("Robert Kubica", "drove_for", "Renault", 0.74),
        scoredTriple("Robert Kubica", "born_in", "Krakow", 0.6),
        scoredTriple("Robert Kubica", "raced_in", "Formula One", 0.82),
        scoredTriple("Robert Kubica", "won", "2008 Canadian Grand Prix", 0.94),
        scoredTriple("Robert Kubica", "drove_for", "Williams", 0.64),
        scoredTriple("BMW Sauber", "competed_in", "Formula One", 0.86),
        scoredTriple("BMW Sauber", "based_in", "Hinwil", 0.68),
        scoredTriple("BMW Sauber", "succeeded", "Sauber", 0.76),
        scoredTriple("BMW Sauber", "had_driver", "Nick Heidfeld", 0.72),
        scoredTriple("BMW Sauber", "used", "BMW P86 engine", 0.66),
        scoredTriple("2008 Canadian Grand Prix", "held_at", "Circuit Gilles Villeneuve", 0.88),
        scoredTriple("Circuit Gilles Villeneuve", "is_in", "Montreal", 0.82),
        scoredTriple("Circuit Gilles Villeneuve", "named_after", "Gilles Villeneuve", 0.64),
        scoredTriple("Nick Heidfeld", "drove_for", "BMW Sauber", 0.7),
        scoredTriple("Nick Heidfeld", "raced_in", "Formula One", 0.62),
        scoredTriple("BMW", "produced", "BMW P86 engine", 0.6),
        scoredTriple("BMW", "based_in", "Munich", 0.74),
        scoredTriple("Sauber", "competed_in", "Formula One", 0.64),
        scoredTriple("Sauber", "based_in", "Hinwil", 0.62),
        scoredTriple("Sauber", "led_by", "Peter Sauber", 0.58),
        scoredTriple("Renault", "competed_in", "Formula One", 0.68),
        scoredTriple("Gerhard Berger", "led", "BMW Motorsport", 0.56),
        scoredTriple("Krakow", "is_in", "Poland", 0.52),
        scoredTriple("RWTH Aachen", "produced", "Mario Theissen", 0.48),
      ],
    },
  },
  "bossy-rookie-selanne": {
    id: "bossy-rookie-selanne",
    canonicalQuestion:
      "Which Finnish-born forward won the same rookie trophy as the player who set the NHL rookie goals record in 1978?",
    expectedAnswer: "Teemu Selanne",
    pathLength: 3,
    hopCount: 3,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "NHL rookie goals record",
          relationship: "set_by",
          node2: "Mike Bossy",
        },
        {
          node1: "Mike Bossy",
          relationship: "won",
          node2: "Calder Trophy",
        },
        {
          node1: "Calder Trophy",
          relationship: "won_by",
          node2: "Teemu Selanne",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("NHL rookie goals record", "set_by", "Mike Bossy", 1.0),
        scoredTriple("Calder Trophy", "belonged_to", "NHL Awards", 0.84),
        scoredTriple("Calder Trophy", "won_by", "Teemu Selanne", 0.78),
        scoredTriple("Calder Trophy", "won_by", "Alexander Ovechkin", 0.66),
        scoredTriple("Calder Trophy", "won_by", "Bobby Orr", 0.62),
        scoredTriple("Calder Trophy", "awarded_in", "NHL", 0.8),
        scoredTriple("Calder Trophy", "named_after", "Frank Calder", 0.58),
        scoredTriple("Calder Trophy", "won_by", "Pavel Bure", 0.7),
        scoredTriple("Calder Trophy", "preceded", "Hart Trophy", 0.48),
        scoredTriple("Mike Bossy", "played_for", "New York Islanders", 0.92),
        scoredTriple("Mike Bossy", "won", "Conn Smythe Trophy", 0.74),
        scoredTriple("Mike Bossy", "born_in", "Montreal", 0.55),
        scoredTriple("Mike Bossy", "played_in", "NHL", 0.82),
        scoredTriple("Mike Bossy", "inducted_into", "Hockey Hall of Fame", 0.64),
        scoredTriple("Teemu Selanne", "played_for", "Winnipeg Jets", 0.86),
        scoredTriple("Teemu Selanne", "played_for", "Anaheim Ducks", 0.79),
        scoredTriple("Teemu Selanne", "born_in", "Helsinki", 0.61),
        scoredTriple("Teemu Selanne", "set", "NHL rookie goals record", 0.92),
        scoredTriple("Winnipeg Jets", "belonged_to", "NHL", 0.72),
        scoredTriple("Winnipeg Jets", "is_in", "Winnipeg", 0.68),
        scoredTriple("Anaheim Ducks", "won", "2007 Stanley Cup", 0.64),
        scoredTriple("New York Islanders", "belonged_to", "NHL", 0.76),
        scoredTriple("New York Islanders", "is_in", "Uniondale", 0.7),
        scoredTriple("New York Islanders", "won", "1982 Stanley Cup", 0.68),
        scoredTriple("Pavel Bure", "played_for", "Vancouver Canucks", 0.72),
        scoredTriple("Pavel Bure", "born_in", "Moscow", 0.55),
        scoredTriple("Bobby Orr", "played_for", "Boston Bruins", 0.74),
        scoredTriple("NHL Awards", "includes", "Hart Trophy", 0.66),
        scoredTriple("NHL Awards", "includes", "Calder Trophy", 0.68),
        scoredTriple("Frank Calder", "led", "NHL", 0.52),
        scoredTriple("Alexander Ovechkin", "played_for", "Washington Capitals", 0.76),
        scoredTriple("Boston Bruins", "belonged_to", "NHL", 0.66),
      ],
    },
  },
  "barrichello-wdc-brackley": {
    id: "barrichello-wdc-brackley",
    canonicalQuestion:
      "In which English town was the constructor that employed the winner of the 2009 Formula One World Championship based?",
    expectedAnswer: "Brackley",
    pathLength: 3,
    hopCount: 3,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "2009 Formula One World Championship",
          relationship: "won_by",
          node2: "Rubens Barrichello",
        },
        {
          node1: "Rubens Barrichello",
          relationship: "drove_for",
          node2: "Brawn GP",
        },
        {
          node1: "Brawn GP",
          relationship: "based_in",
          node2: "Brackley",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2009 Formula One World Championship", "won_by", "Jenson Button", 1.0),
        scoredTriple("Rubens Barrichello", "drove_for", "Brawn GP", 1.0),
        scoredTriple("Brawn GP", "based_in", "Brackley", 1.0),
        scoredTriple("Brawn GP", "led_by", "Ross Brawn", 0.88),
        scoredTriple("Brawn GP", "won", "2009 Constructors Championship", 0.86),
        scoredTriple("Brawn GP", "succeeded", "Honda Racing", 0.78),
        scoredTriple("Brawn GP", "preceded", "Mercedes GP", 0.74),
        scoredTriple("Brawn GP", "used", "Mercedes engine", 0.68),
        scoredTriple("Brawn GP", "had_driver", "Jenson Button", 0.82),
        scoredTriple("Brawn GP", "competed_in", "Formula One", 0.8),
        scoredTriple("Rubens Barrichello", "drove_for", "Ferrari", 0.84),
        scoredTriple("Rubens Barrichello", "drove_for", "Williams", 0.62),
        scoredTriple("Rubens Barrichello", "born_in", "Sao Paulo", 0.58),
        scoredTriple("Rubens Barrichello", "raced_in", "Formula One", 0.76),
        scoredTriple("Rubens Barrichello", "set", "Most F1 race starts record", 0.64),
        scoredTriple("Jenson Button", "drove_for", "McLaren", 0.7),
        scoredTriple("Jenson Button", "born_in", "Frome", 0.52),
        scoredTriple("Ross Brawn", "led", "Ferrari", 0.72),
        scoredTriple("Ross Brawn", "led", "Mercedes GP", 0.66),
        scoredTriple("Honda Racing", "competed_in", "Formula One", 0.64),
        scoredTriple("Brackley", "hosts", "Honda Racing", 0.6),
        scoredTriple("Brackley", "hosts", "Brawn GP", 0.58),
        scoredTriple("Brackley", "known_for", "Northamptonshire motorsport", 0.52),
        scoredTriple("Ferrari", "competed_in", "Formula One", 0.78),
        scoredTriple("Ferrari", "based_in", "Maranello", 0.74),
        scoredTriple("Mercedes GP", "competed_in", "Formula One", 0.7),
        scoredTriple("Mercedes engine", "produced_by", "Mercedes-Benz", 0.62),
        scoredTriple("McLaren", "competed_in", "Formula One", 0.66),
        scoredTriple("McLaren", "based_in", "Woking", 0.58),
        scoredTriple("Sao Paulo", "contains", "Interlagos", 0.56),
        scoredTriple("Interlagos", "hosts", "Formula One", 0.52),
        scoredTriple("Formula One", "governed_by", "FIA", 0.54),
        scoredTriple("Brackley", "is_in", "Northamptonshire", 0.5),
        scoredTriple("Williams", "competed_in", "Formula One", 0.6),
      ],
    },
  },
  "boli-marseille-goethals": {
    id: "boli-marseille-goethals",
    canonicalQuestion:
      "Who managed the club that won the tournament where Abedi Pele was named best player in 1993?",
    expectedAnswer: "Raymond Goethals",
    pathLength: 3,
    hopCount: 3,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "1993 Champions League Best Player",
          relationship: "won_by",
          node2: "Basile Boli",
        },
        {
          node1: "Basile Boli",
          relationship: "played_for",
          node2: "Olympique de Marseille",
        },
        {
          node1: "Olympique de Marseille",
          relationship: "managed_by",
          node2: "Raymond Goethals",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("1993 Champions League Best Player", "won_by", "Basile Boli", 1.0),
        scoredTriple("Basile Boli", "played_for", "Olympique de Marseille", 1.0),
        scoredTriple("Raymond Goethals", "born_in", "Brussels", 0.62),
        scoredTriple("Raymond Goethals", "managed", "Standard Liege", 0.74),
        scoredTriple("Raymond Goethals", "managed", "Bordeaux", 0.7),
        scoredTriple("Raymond Goethals", "managed", "Belgium national team", 0.66),
        scoredTriple("Raymond Goethals", "won", "1993 Champions League", 0.82),
        scoredTriple("Raymond Goethals", "belonged_to", "Belgian football managers", 0.56),
        scoredTriple("Raymond Goethals", "succeeded", "Franz Beckenbauer", 0.52),
        scoredTriple("Raymond Goethals", "coached_in", "Ligue 1", 0.48),
        scoredTriple("Basile Boli", "won", "1993 Champions League", 0.82),
        scoredTriple("Basile Boli", "played_for", "France national team", 0.7),
        scoredTriple("Basile Boli", "born_in", "Abidjan", 0.52),
        scoredTriple("Abedi Pele", "played_for", "Olympique de Marseille", 0.88),
        scoredTriple("Abedi Pele", "won", "African Footballer of the Year", 0.8),
        scoredTriple("Abedi Pele", "played_for", "Ghana national team", 0.84),
        scoredTriple("Abedi Pele", "won", "1993 Champions League Best Player", 0.9),
        scoredTriple("Olympique de Marseille", "won", "1993 Champions League", 0.92),
        scoredTriple("Olympique de Marseille", "is_in", "Marseille", 0.84),
        scoredTriple("Olympique de Marseille", "belonged_to", "Ligue 1", 0.82),
        scoredTriple("Olympique de Marseille", "used", "Stade Velodrome", 0.78),
        scoredTriple("Olympique de Marseille", "had_player", "Abedi Pele", 0.76),
        scoredTriple("AC Milan", "played_in", "1993 Champions League", 0.64),
        scoredTriple("AC Milan", "played_in", "1993 Champions League final", 0.58),
        scoredTriple("Ghana national team", "belonged_to", "CAF", 0.56),
        scoredTriple("Standard Liege", "is_in", "Liege", 0.6),
        scoredTriple("Bordeaux", "belonged_to", "Ligue 1", 0.64),
        scoredTriple("Stade Velodrome", "is_in", "Marseille", 0.72),
        scoredTriple("Ligue 1", "includes", "Olympique de Marseille", 0.6),
        scoredTriple("France national team", "had_player", "Basile Boli", 0.58),
        scoredTriple("Abidjan", "produced", "Basile Boli", 0.46),
      ],
    },
  },
  "horry-mvp-tomjanovich": {
    id: "horry-mvp-tomjanovich",
    canonicalQuestion:
      "Who was the head coach of the team that drafted the player who won the 1994 NBA Finals MVP?",
    expectedAnswer: "Rudy Tomjanovich",
    pathLength: 3,
    hopCount: 3,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "1994 NBA Finals MVP",
          relationship: "won_by",
          node2: "Hakeem Olajuwon",
        },
        {
          node1: "Hakeem Olajuwon",
          relationship: "played_for",
          node2: "Houston Rockets",
        },
        {
          node1: "Houston Rockets",
          relationship: "coached_by",
          node2: "Rudy Tomjanovich",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("1994 NBA Finals MVP", "won_by", "Robert Horry", 1.0),
        scoredTriple("Robert Horry", "played_for", "Houston Rockets", 1.0),
        scoredTriple("Rudy Tomjanovich", "won", "1994 NBA Championship", 0.84),
        scoredTriple("Rudy Tomjanovich", "won", "1995 NBA Championship", 0.8),
        scoredTriple("Rudy Tomjanovich", "played_for", "Houston Rockets", 0.72),
        scoredTriple("Rudy Tomjanovich", "coached", "Los Angeles Lakers", 0.58),
        scoredTriple("Rudy Tomjanovich", "belonged_to", "NBA coaches", 0.54),
        scoredTriple("Rudy Tomjanovich", "inducted_into", "Basketball Hall of Fame", 0.52),
        scoredTriple("Rudy Tomjanovich", "born_in", "Hamtramck", 0.48),
        scoredTriple("Robert Horry", "played_for", "Los Angeles Lakers", 0.78),
        scoredTriple("Robert Horry", "played_for", "San Antonio Spurs", 0.72),
        scoredTriple("Robert Horry", "won", "1994 NBA Championship", 0.82),
        scoredTriple("Robert Horry", "played_in", "NBA", 0.76),
        scoredTriple("Robert Horry", "studied_at", "University of Alabama", 0.58),
        scoredTriple("Hakeem Olajuwon", "won", "1994 NBA Finals MVP", 0.92),
        scoredTriple("Hakeem Olajuwon", "played_for", "Houston Rockets", 0.9),
        scoredTriple("Hakeem Olajuwon", "won", "1994 NBA Championship", 0.86),
        scoredTriple("Hakeem Olajuwon", "played_in", "NBA", 0.84),
        scoredTriple("Houston Rockets", "belonged_to", "NBA", 0.82),
        scoredTriple("Houston Rockets", "is_in", "Houston", 0.78),
        scoredTriple("Houston Rockets", "won", "1994 NBA Championship", 0.84),
        scoredTriple("Houston Rockets", "had_player", "Hakeem Olajuwon", 0.88),
        scoredTriple("Houston Rockets", "used", "The Summit", 0.62),
        scoredTriple("Los Angeles Lakers", "belonged_to", "NBA", 0.7),
        scoredTriple("San Antonio Spurs", "belonged_to", "NBA", 0.66),
        scoredTriple("1994 NBA Championship", "had_finalist", "New York Knicks", 0.72),
        scoredTriple("New York Knicks", "belonged_to", "NBA", 0.64),
        scoredTriple("University of Alabama", "produced", "Robert Horry", 0.52),
        scoredTriple("NBA", "includes", "Houston Rockets", 0.56),
        scoredTriple("NBA coaches", "includes", "Rudy Tomjanovich", 0.5),
        scoredTriple("Houston", "home_of", "Houston Rockets", 0.68),
        scoredTriple("Houston Rockets", "had_player", "Robert Horry", 0.74),
        scoredTriple("Clyde Drexler", "played_for", "Houston Rockets", 0.66),
        scoredTriple("Clyde Drexler", "won", "1995 NBA Championship", 0.62),
      ],
    },
  },
  "savicevic-milan-baresi": {
    id: "savicevic-milan-baresi",
    canonicalQuestion:
      "Who captained the club that won the league managed by the coach who employed Dejan Savicevic after his time at Red Star Belgrade?",
    expectedAnswer: "Franco Baresi",
    pathLength: 4,
    hopCount: 4,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "Dejan Savicevic",
          relationship: "joined",
          node2: "AC Milan",
        },
        {
          node1: "AC Milan",
          relationship: "managed_by",
          node2: "Fabio Capello",
        },
        {
          node1: "Fabio Capello",
          relationship: "won",
          node2: "1993-94 Serie A",
        },
        {
          node1: "1993-94 Serie A",
          relationship: "captained_by",
          node2: "Franco Baresi",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Dejan Savicevic", "joined", "AC Milan", 1.0),
        scoredTriple("AC Milan", "managed_by", "Fabio Capello", 1.0),
        scoredTriple("Fabio Capello", "won", "1993-94 Serie A", 1.0),
        scoredTriple("1993-94 Serie A", "captained_by", "Franco Baresi", 1.0),
        scoredTriple("Franco Baresi", "played_for", "AC Milan", 0.92),
        scoredTriple("Franco Baresi", "played_for", "Italy national team", 0.78),
        scoredTriple("Franco Baresi", "was_runner_up_in", "1994 FIFA World Cup", 0.62),
        scoredTriple("Franco Baresi", "played_in", "Serie A", 0.66),
        scoredTriple("Franco Baresi", "preceded", "Paolo Maldini", 0.72),
        scoredTriple("Franco Baresi", "captained", "AC Milan", 0.84),
        scoredTriple("Franco Baresi", "belonged_to", "Ballon d'Or nominees", 0.52),
        scoredTriple("Franco Baresi", "born_in", "Travagliato", 0.48),
        scoredTriple("Dejan Savicevic", "played_for", "Red Star Belgrade", 0.86),
        scoredTriple("Dejan Savicevic", "won", "1991 European Cup", 0.82),
        scoredTriple("Dejan Savicevic", "played_for", "Yugoslavia national team", 0.74),
        scoredTriple("Dejan Savicevic", "born_in", "Titograd", 0.54),
        scoredTriple("AC Milan", "is_in", "Milan", 0.88),
        scoredTriple("AC Milan", "played_in", "Serie A", 0.9),
        scoredTriple("AC Milan", "used", "San Siro", 0.82),
        scoredTriple("AC Milan", "won", "1994 Champions League", 0.78),
        scoredTriple("AC Milan", "had_player", "Paolo Maldini", 0.8),
        scoredTriple("Fabio Capello", "managed", "Real Madrid", 0.72),
        scoredTriple("Fabio Capello", "managed", "England national team", 0.66),
        scoredTriple("Fabio Capello", "managed", "Juventus", 0.68),
        scoredTriple("Fabio Capello", "belonged_to", "Italian football managers", 0.56),
        scoredTriple("Red Star Belgrade", "won", "1991 European Cup", 0.84),
        scoredTriple("Red Star Belgrade", "is_in", "Belgrade", 0.8),
        scoredTriple("Paolo Maldini", "played_for", "AC Milan", 0.88),
        scoredTriple("Paolo Maldini", "succeeded", "Franco Baresi", 0.7),
        scoredTriple("1994 Champions League", "won_by", "AC Milan", 0.64),
        scoredTriple("Serie A", "includes", "AC Milan", 0.72),
        scoredTriple("Juventus", "played_in", "Serie A", 0.74),
        scoredTriple("San Siro", "is_in", "Milan", 0.76),
      ],
    },
  },
  "kubica-bmw-reithofer": {
    id: "kubica-bmw-reithofer",
    canonicalQuestion:
      "Who was the CEO of the parent company of the constructor that employed Robert Kubica when he won his only Grand Prix?",
    expectedAnswer: "Norbert Reithofer",
    pathLength: 4,
    hopCount: 4,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2008 Canadian Grand Prix",
          relationship: "won_by",
          node2: "Robert Kubica",
        },
        {
          node1: "Robert Kubica",
          relationship: "drove_for",
          node2: "BMW Sauber",
        },
        {
          node1: "BMW Sauber",
          relationship: "owned_by",
          node2: "BMW",
        },
        {
          node1: "BMW",
          relationship: "led_by",
          node2: "Norbert Reithofer",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2008 Canadian Grand Prix", "won_by", "Robert Kubica", 1.0),
        scoredTriple("Robert Kubica", "drove_for", "BMW Sauber", 1.0),
        scoredTriple("BMW Sauber", "owned_by", "BMW", 1.0),
        scoredTriple("BMW", "led_by", "Norbert Reithofer", 1.0),
        scoredTriple("Norbert Reithofer", "succeeded", "Helmut Panke", 0.72),
        scoredTriple("Norbert Reithofer", "preceded", "Harald Krueger", 0.68),
        scoredTriple("Norbert Reithofer", "born_in", "Penzberg", 0.52),
        scoredTriple("Norbert Reithofer", "studied_at", "Technical University of Munich", 0.58),
        scoredTriple("Norbert Reithofer", "served_on", "BMW Board", 0.64),
        scoredTriple("Norbert Reithofer", "belonged_to", "Unternehmer", 0.5),
        scoredTriple("Robert Kubica", "drove_for", "Renault", 0.74),
        scoredTriple("Robert Kubica", "drove_for", "Williams", 0.64),
        scoredTriple("Robert Kubica", "born_in", "Krakow", 0.6),
        scoredTriple("Robert Kubica", "raced_in", "Formula One", 0.82),
        scoredTriple("BMW Sauber", "based_in", "Hinwil", 0.7),
        scoredTriple("BMW Sauber", "had_driver", "Nick Heidfeld", 0.72),
        scoredTriple("BMW Sauber", "led_by", "Mario Theissen", 0.78),
        scoredTriple("BMW Sauber", "succeeded", "Sauber", 0.76),
        scoredTriple("BMW", "based_in", "Munich", 0.82),
        scoredTriple("BMW", "produced", "BMW P86 engine", 0.66),
        scoredTriple("BMW", "founded", "BMW Motorsport", 0.62),
        scoredTriple("BMW", "has", "BMW Board", 0.58),
        scoredTriple("2008 Canadian Grand Prix", "held_at", "Circuit Gilles Villeneuve", 0.86),
        scoredTriple("Circuit Gilles Villeneuve", "is_in", "Montreal", 0.82),
        scoredTriple("Nick Heidfeld", "drove_for", "BMW Sauber", 0.7),
        scoredTriple("Mario Theissen", "led", "BMW Motorsport", 0.72),
        scoredTriple("Sauber", "competed_in", "Formula One", 0.64),
        scoredTriple("Helmut Panke", "led", "BMW", 0.6),
        scoredTriple("Renault", "competed_in", "Formula One", 0.68),
        scoredTriple("BMW Motorsport", "owned_by", "BMW", 0.66),
        scoredTriple("Munich", "home_of", "Technical University of Munich", 0.56),
        scoredTriple("Formula One", "includes", "BMW Sauber", 0.54),
      ],
    },
  },
  "rivera-yankees-brooklyn": {
    id: "rivera-yankees-brooklyn",
    canonicalQuestion:
      "In which New York borough was the manager of the team that employed the closer with the most postseason saves in MLB history born?",
    expectedAnswer: "Brooklyn",
    pathLength: 4,
    hopCount: 4,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "Postseason Saves Record",
          relationship: "set_by",
          node2: "Mariano Rivera",
        },
        {
          node1: "Mariano Rivera",
          relationship: "played_for",
          node2: "New York Yankees",
        },
        {
          node1: "New York Yankees",
          relationship: "managed_by",
          node2: "Joe Torre",
        },
        {
          node1: "Joe Torre",
          relationship: "born_in",
          node2: "Brooklyn",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Postseason Saves Record", "set_by", "Mariano Rivera", 1.0),
        scoredTriple("Mariano Rivera", "played_for", "New York Yankees", 1.0),
        scoredTriple("New York Yankees", "managed_by", "Joe Torre", 1.0),
        scoredTriple("Joe Torre", "born_in", "Brooklyn", 1.0),
        scoredTriple("Joe Torre", "managed", "St. Louis Cardinals", 0.76),
        scoredTriple("Joe Torre", "managed", "New York Mets", 0.72),
        scoredTriple("Joe Torre", "won", "1971 National League MVP", 0.78),
        scoredTriple("Joe Torre", "inducted_into", "Baseball Hall of Fame", 0.68),
        scoredTriple("Joe Torre", "succeeded", "Buck Showalter", 0.6),
        scoredTriple("Mariano Rivera", "won", "1999 World Series MVP", 0.82),
        scoredTriple("Mariano Rivera", "played_in", "MLB", 0.86),
        scoredTriple("Mariano Rivera", "born_in", "Panama City", 0.58),
        scoredTriple("Mariano Rivera", "inducted_into", "Baseball Hall of Fame", 0.74),
        scoredTriple("Mariano Rivera", "set", "MLB saves record", 0.8),
        scoredTriple("New York Yankees", "belonged_to", "MLB", 0.9),
        scoredTriple("New York Yankees", "based_in", "Bronx", 0.84),
        scoredTriple("New York Yankees", "used", "Yankee Stadium", 0.86),
        scoredTriple("New York Yankees", "won", "1998 World Series", 0.82),
        scoredTriple("New York Yankees", "had_player", "Derek Jeter", 0.82),
        scoredTriple("Brooklyn", "is_in", "New York City", 0.84),
        scoredTriple("Brooklyn", "produced", "Sandy Koufax", 0.64),
        scoredTriple("Brooklyn", "home_of", "Ebbets Field", 0.66),
        scoredTriple("Ebbets Field", "home_of", "Brooklyn Dodgers", 0.6),
        scoredTriple("Derek Jeter", "played_for", "New York Yankees", 0.84),
        scoredTriple("Derek Jeter", "won", "2000 World Series MVP", 0.72),
        scoredTriple("St. Louis Cardinals", "belonged_to", "MLB", 0.7),
        scoredTriple("New York Mets", "belonged_to", "MLB", 0.72),
        scoredTriple("Buck Showalter", "managed", "New York Yankees", 0.64),
        scoredTriple("Bronx", "home_of", "Yankee Stadium", 0.76),
        scoredTriple("New York City", "contains", "Bronx", 0.8),
        scoredTriple("1998 World Series", "had_finalist", "San Diego Padres", 0.66),
        scoredTriple("MLB", "includes", "New York Yankees", 0.58),
        scoredTriple("Brooklyn Dodgers", "belonged_to", "MLB", 0.52),
        scoredTriple("Sandy Koufax", "played_for", "Brooklyn Dodgers", 0.58),
      ],
    },
  },
  "hamilton-mercedes-vienna": {
    id: "hamilton-mercedes-vienna",
    canonicalQuestion:
      "In which European capital was the team principal of the constructor that employed the winner of the 2014 Formula One World Championship born?",
    expectedAnswer: "Vienna",
    pathLength: 4,
    hopCount: 4,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2014 Formula One World Championship",
          relationship: "won_by",
          node2: "Lewis Hamilton",
        },
        {
          node1: "Lewis Hamilton",
          relationship: "drove_for",
          node2: "Mercedes AMG F1",
        },
        {
          node1: "Mercedes AMG F1",
          relationship: "led_by",
          node2: "Toto Wolff",
        },
        {
          node1: "Toto Wolff",
          relationship: "born_in",
          node2: "Vienna",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2014 Formula One World Championship", "won_by", "Lewis Hamilton", 1.0),
        scoredTriple("Lewis Hamilton", "drove_for", "Mercedes AMG F1", 1.0),
        scoredTriple("Mercedes AMG F1", "led_by", "Toto Wolff", 1.0),
        scoredTriple("Toto Wolff", "born_in", "Vienna", 1.0),
        scoredTriple("Toto Wolff", "led", "Williams F1", 0.72),
        scoredTriple("Toto Wolff", "belonged_to", "Austrian motorsport executives", 0.58),
        scoredTriple("Toto Wolff", "succeeded", "Ross Brawn", 0.66),
        scoredTriple("Toto Wolff", "studied_at", "Vienna University of Economics", 0.56),
        scoredTriple("Lewis Hamilton", "drove_for", "McLaren", 0.78),
        scoredTriple("Lewis Hamilton", "won", "2008 F1 World Championship", 0.82),
        scoredTriple("Lewis Hamilton", "born_in", "Stevenage", 0.6),
        scoredTriple("Lewis Hamilton", "raced_in", "F1", 0.86),
        scoredTriple("Mercedes AMG F1", "based_in", "Brackley", 0.82),
        scoredTriple("Mercedes AMG F1", "competed_in", "F1", 0.88),
        scoredTriple("Mercedes AMG F1", "succeeded", "Brawn GP", 0.78),
        scoredTriple("Mercedes AMG F1", "won", "2014 Constructors Championship", 0.84),
        scoredTriple("Mercedes AMG F1", "used", "Mercedes PU106A Hybrid", 0.66),
        scoredTriple("Mercedes AMG F1", "had_driver", "Nico Rosberg", 0.78),
        scoredTriple("Vienna", "home_of", "Vienna University of Economics", 0.64),
        scoredTriple("Vienna", "produced", "Niki Lauda", 0.7),
        scoredTriple("Vienna", "capital_of", "Austria", 0.6),
        scoredTriple("Vienna", "produced", "Austrian motorsport executives", 0.54),
        scoredTriple("Niki Lauda", "led", "Mercedes AMG F1", 0.76),
        scoredTriple("Niki Lauda", "won", "1984 F1 World Championship", 0.72),
        scoredTriple("Niki Lauda", "drove_for", "Ferrari", 0.68),
        scoredTriple("Nico Rosberg", "won", "2016 F1 World Championship", 0.74),
        scoredTriple("Williams F1", "competed_in", "F1", 0.7),
        scoredTriple("McLaren", "competed_in", "F1", 0.68),
        scoredTriple("Brawn GP", "competed_in", "F1", 0.64),
        scoredTriple("Ross Brawn", "led", "Mercedes AMG F1", 0.66),
        scoredTriple("Stevenage", "is_in", "Hertfordshire", 0.56),
        scoredTriple("2014 Constructors Championship", "awarded_in", "F1", 0.62),
        scoredTriple("F1", "includes", "Mercedes AMG F1", 0.6),
      ],
    },
  },
  "tortorella-tampa-iginla": {
    id: "tortorella-tampa-iginla",
    canonicalQuestion:
      "Who captained the team that lost the Stanley Cup Final to the club coached by the winner of the 2004 Jack Adams Award?",
    expectedAnswer: "Jarome Iginla",
    pathLength: 4,
    hopCount: 4,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "2004 Jack Adams Award",
          relationship: "won_by",
          node2: "John Tortorella",
        },
        {
          node1: "John Tortorella",
          relationship: "coached",
          node2: "Tampa Bay Lightning",
        },
        {
          node1: "Tampa Bay Lightning",
          relationship: "defeated",
          node2: "Philadelphia Flyers",
        },
        {
          node1: "Philadelphia Flyers",
          relationship: "captained_by",
          node2: "Jarome Iginla",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2004 Jack Adams Award", "won_by", "John Tortorella", 1.0),
        scoredTriple("John Tortorella", "coached", "Tampa Bay Lightning", 1.0),
        scoredTriple("Jarome Iginla", "played_for", "Calgary Flames", 0.92),
        scoredTriple("Jarome Iginla", "won", "Rocket Richard Trophy", 0.76),
        scoredTriple("Jarome Iginla", "won", "Art Ross Trophy", 0.72),
        scoredTriple("Jarome Iginla", "played_in", "NHL", 0.84),
        scoredTriple("Jarome Iginla", "played_for", "Pittsburgh Penguins", 0.62),
        scoredTriple("Jarome Iginla", "born_in", "Edmonton", 0.54),
        scoredTriple("Jarome Iginla", "played_for", "Canada national team", 0.68),
        scoredTriple("John Tortorella", "coached", "New York Rangers", 0.74),
        scoredTriple("John Tortorella", "coached", "Vancouver Canucks", 0.66),
        scoredTriple("John Tortorella", "coached", "Columbus Blue Jackets", 0.6),
        scoredTriple("John Tortorella", "belonged_to", "NHL coaches", 0.58),
        scoredTriple("Tampa Bay Lightning", "won", "2004 Stanley Cup", 0.9),
        scoredTriple("Tampa Bay Lightning", "based_in", "Tampa", 0.78),
        scoredTriple("Tampa Bay Lightning", "belonged_to", "NHL", 0.82),
        scoredTriple("Tampa Bay Lightning", "had_player", "Vincent Lecavalier", 0.76),
        scoredTriple("Tampa Bay Lightning", "had_player", "Brad Richards", 0.74),
        scoredTriple("Calgary Flames", "lost_to", "Tampa Bay Lightning", 0.7),
        scoredTriple("Calgary Flames", "based_in", "Calgary", 0.8),
        scoredTriple("Calgary Flames", "belonged_to", "NHL", 0.78),
        scoredTriple("Calgary Flames", "had_player", "Jarome Iginla", 0.86),
        scoredTriple("Calgary Flames", "used", "Pengrowth Saddledome", 0.64),
        scoredTriple("Philadelphia Flyers", "based_in", "Philadelphia", 0.8),
        scoredTriple("Philadelphia Flyers", "belonged_to", "NHL", 0.78),
        scoredTriple("Philadelphia Flyers", "used", "Wachovia Center", 0.66),
        scoredTriple("Brad Richards", "won", "Conn Smythe Trophy", 0.72),
        scoredTriple("Vincent Lecavalier", "won", "Rocket Richard Trophy", 0.6),
        scoredTriple("2004 Stanley Cup", "awarded_in", "NHL", 0.68),
        scoredTriple("Canada national team", "had_player", "Jarome Iginla", 0.62),
        scoredTriple("Pittsburgh Penguins", "belonged_to", "NHL", 0.58),
        scoredTriple("New York Rangers", "belonged_to", "NHL", 0.56),
        scoredTriple("Edmonton", "produced", "Jarome Iginla", 0.46),
      ],
    },
  },
  "olajuwon-draft-williams": {
    id: "olajuwon-draft-williams",
    canonicalQuestion:
      "Who was the head coach of the college team that produced the player who was drafted first overall in the year Hakeem Olajuwon won his first NBA championship?",
    expectedAnswer: "Gary Williams",
    pathLength: 4,
    hopCount: 4,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "Hakeem Olajuwon",
          relationship: "won",
          node2: "1995 NBA Championship",
        },
        {
          node1: "1995 NBA Championship",
          relationship: "same_year_as",
          node2: "1995 NBA Draft",
        },
        {
          node1: "1995 NBA Draft",
          relationship: "first_pick_was",
          node2: "Joe Smith",
        },
        {
          node1: "Joe Smith",
          relationship: "played_for",
          node2: "University of North Carolina",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Hakeem Olajuwon", "won", "1995 NBA Championship", 1.0),
        scoredTriple("1995 NBA Championship", "same_year_as", "1995 NBA Draft", 1.0),
        scoredTriple("1995 NBA Draft", "first_pick_was", "Joe Smith", 1.0),
        scoredTriple("Gary Williams", "coached", "University of Maryland", 0.88),
        scoredTriple("Gary Williams", "won", "2002 NCAA Championship", 0.78),
        scoredTriple("Gary Williams", "belonged_to", "NCAA coaches", 0.62),
        scoredTriple("Gary Williams", "coached_in", "ACC", 0.56),
        scoredTriple("Gary Williams", "born_in", "Collingswood", 0.48),
        scoredTriple("Gary Williams", "preceded", "Mark Turgeon", 0.52),
        scoredTriple("Gary Williams", "studied_at", "University of Maryland", 0.6),
        scoredTriple("Hakeem Olajuwon", "played_for", "Houston Rockets", 0.92),
        scoredTriple("Hakeem Olajuwon", "won", "1994 NBA Championship", 0.86),
        scoredTriple("Hakeem Olajuwon", "played_in", "NBA", 0.84),
        scoredTriple("Hakeem Olajuwon", "played_for", "University of Houston", 0.78),
        scoredTriple("Joe Smith", "played_for", "Golden State Warriors", 0.82),
        scoredTriple("Joe Smith", "played_for", "University of Maryland", 0.88),
        scoredTriple("Joe Smith", "played_in", "NBA", 0.74),
        scoredTriple("Joe Smith", "won", "Naismith Award", 0.66),
        scoredTriple("University of Maryland", "belonged_to", "ACC", 0.8),
        scoredTriple("University of Maryland", "is_in", "College Park", 0.72),
        scoredTriple("University of Maryland", "produced", "Joe Smith", 0.84),
        scoredTriple("University of Maryland", "won", "2002 NCAA Championship", 0.76),
        scoredTriple("University of North Carolina", "belonged_to", "ACC", 0.82),
        scoredTriple("University of North Carolina", "is_in", "Chapel Hill", 0.74),
        scoredTriple("University of North Carolina", "coached_by", "Dean Smith", 0.7),
        scoredTriple("University of North Carolina", "produced", "Michael Jordan", 0.68),
        scoredTriple("Golden State Warriors", "belonged_to", "NBA", 0.76),
        scoredTriple("Golden State Warriors", "based_in", "Oakland", 0.72),
        scoredTriple("Houston Rockets", "won", "1995 NBA Championship", 0.88),
        scoredTriple("1995 NBA Draft", "belonged_to", "NBA", 0.64),
        scoredTriple("ACC", "includes", "University of Maryland", 0.62),
        scoredTriple("Dean Smith", "belonged_to", "NCAA coaches", 0.56),
        scoredTriple("Michael Jordan", "played_in", "NBA", 0.58),
      ],
    },
  },
  "brady-patriots-nashville": {
    id: "brady-patriots-nashville",
    canonicalQuestion:
      "In which Southern city was the head coach of the franchise of the Super Bowl XXXIX MVP born?",
    expectedAnswer: "Nashville",
    pathLength: 4,
    hopCount: 4,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "Super Bowl XXXIX MVP",
          relationship: "won_by",
          node2: "Tom Brady",
        },
        {
          node1: "Tom Brady",
          relationship: "played_for",
          node2: "New England Patriots",
        },
        {
          node1: "New England Patriots",
          relationship: "coached_by",
          node2: "Bill Belichick",
        },
        {
          node1: "Bill Belichick",
          relationship: "born_in",
          node2: "Nashville",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Super Bowl XXXIX MVP", "won_by", "Deion Branch", 1.0),
        scoredTriple("Tom Brady", "played_for", "New England Patriots", 1.0),
        scoredTriple("New England Patriots", "coached_by", "Bill Belichick", 1.0),
        scoredTriple("Bill Belichick", "born_in", "Nashville", 1.0),
        scoredTriple("Bill Belichick", "coached", "Cleveland Browns", 0.74),
        scoredTriple("Bill Belichick", "succeeded", "Pete Carroll", 0.66),
        scoredTriple("Bill Belichick", "won", "Super Bowl XXXIX", 0.86),
        scoredTriple("Bill Belichick", "belonged_to", "NFL coaches", 0.62),
        scoredTriple("Bill Belichick", "studied_at", "Wesleyan University", 0.56),
        scoredTriple("Tom Brady", "won", "Super Bowl XLIX", 0.84),
        scoredTriple("Tom Brady", "born_in", "San Mateo", 0.58),
        scoredTriple("Tom Brady", "played_in", "NFL", 0.86),
        scoredTriple("Tom Brady", "played_for", "Tampa Bay Buccaneers", 0.74),
        scoredTriple("Tom Brady", "studied_at", "University of Michigan", 0.66),
        scoredTriple("Deion Branch", "played_for", "New England Patriots", 0.82),
        scoredTriple("Deion Branch", "won", "Super Bowl XXXIX", 0.8),
        scoredTriple("Deion Branch", "played_for", "Seattle Seahawks", 0.7),
        scoredTriple("New England Patriots", "won", "Super Bowl XXXIX", 0.88),
        scoredTriple("New England Patriots", "based_in", "Foxborough", 0.8),
        scoredTriple("New England Patriots", "belonged_to", "NFL", 0.86),
        scoredTriple("New England Patriots", "used", "Gillette Stadium", 0.78),
        scoredTriple("New England Patriots", "had_player", "Rob Gronkowski", 0.74),
        scoredTriple("Nashville", "home_of", "Nissan Stadium", 0.62),
        scoredTriple("Nashville", "produced", "Bill Belichick", 0.66),
        scoredTriple("Nashville", "home_of", "Tennessee Titans", 0.58),
        scoredTriple("Nashville", "capital_of", "Tennessee", 0.6),
        scoredTriple("Super Bowl XXXIX", "had_finalist", "Philadelphia Eagles", 0.68),
        scoredTriple("Philadelphia Eagles", "belonged_to", "NFL", 0.64),
        scoredTriple("Cleveland Browns", "belonged_to", "NFL", 0.6),
        scoredTriple("Pete Carroll", "coached", "Seattle Seahawks", 0.66),
        scoredTriple("Wesleyan University", "produced", "Bill Belichick", 0.52),
        scoredTriple("Rob Gronkowski", "played_in", "NFL", 0.62),
        scoredTriple("Tennessee Titans", "belonged_to", "NFL", 0.58),
        scoredTriple("Gillette Stadium", "is_in", "Foxborough", 0.64),
        scoredTriple("Super Bowl XXXIX MVP", "belonged_to", "NFL Awards", 0.62),
      ],
    },
  },
  "erving-sixers-brooklyn": {
    id: "erving-sixers-brooklyn",
    canonicalQuestion:
      "In which New York borough was the head coach of the 1983 NBA Finals MVP's franchise born?",
    expectedAnswer: "Brooklyn",
    pathLength: 4,
    hopCount: 4,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "1983 NBA Finals MVP",
          relationship: "won_by",
          node2: "Julius Erving",
        },
        {
          node1: "Julius Erving",
          relationship: "played_for",
          node2: "Philadelphia 76ers",
        },
        {
          node1: "Philadelphia 76ers",
          relationship: "coached_by",
          node2: "Billy Cunningham",
        },
        {
          node1: "Billy Cunningham",
          relationship: "born_in",
          node2: "Brooklyn",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("1983 NBA Finals MVP", "won_by", "Moses Malone", 1.0),
        scoredTriple("Julius Erving", "played_for", "Philadelphia 76ers", 1.0),
        scoredTriple("Philadelphia 76ers", "coached_by", "Billy Cunningham", 1.0),
        scoredTriple("Billy Cunningham", "born_in", "Brooklyn", 1.0),
        scoredTriple("Billy Cunningham", "played_for", "Philadelphia 76ers", 0.78),
        scoredTriple("Billy Cunningham", "won", "1967 NBA Championship", 0.74),
        scoredTriple("Billy Cunningham", "inducted_into", "Basketball Hall of Fame", 0.68),
        scoredTriple("Billy Cunningham", "coached", "Miami Heat", 0.54),
        scoredTriple("Billy Cunningham", "succeeded", "Gene Shue", 0.58),
        scoredTriple("Julius Erving", "played_for", "New York Nets", 0.8),
        scoredTriple("Julius Erving", "won", "1981 NBA MVP", 0.82),
        scoredTriple("Julius Erving", "played_in", "NBA", 0.86),
        scoredTriple("Julius Erving", "born_in", "Roosevelt", 0.58),
        scoredTriple("Julius Erving", "inducted_into", "Basketball Hall of Fame", 0.72),
        scoredTriple("Moses Malone", "played_for", "Philadelphia 76ers", 0.82),
        scoredTriple("Moses Malone", "won", "1983 NBA Championship", 0.8),
        scoredTriple("Moses Malone", "played_in", "NBA", 0.78),
        scoredTriple("Moses Malone", "won", "1979 NBA MVP", 0.7),
        scoredTriple("Philadelphia 76ers", "belonged_to", "NBA", 0.88),
        scoredTriple("Philadelphia 76ers", "based_in", "Philadelphia", 0.84),
        scoredTriple("Philadelphia 76ers", "won", "1983 NBA Championship", 0.86),
        scoredTriple("Philadelphia 76ers", "used", "Wells Fargo Center", 0.7),
        scoredTriple("Philadelphia 76ers", "had_player", "Charles Barkley", 0.72),
        scoredTriple("Brooklyn", "produced", "Billy Cunningham", 0.64),
        scoredTriple("Brooklyn", "home_of", "Barclays Center", 0.6),
        scoredTriple("Brooklyn", "home_of", "New York Nets", 0.56),
        scoredTriple("Brooklyn", "home_of", "Brooklyn Nets", 0.58),
        scoredTriple("New York Nets", "belonged_to", "NBA", 0.66),
        scoredTriple("1983 NBA Championship", "had_finalist", "Los Angeles Lakers", 0.72),
        scoredTriple("Los Angeles Lakers", "belonged_to", "NBA", 0.74),
        scoredTriple("Charles Barkley", "played_for", "Philadelphia 76ers", 0.68),
        scoredTriple("Miami Heat", "belonged_to", "NBA", 0.62),
        scoredTriple("Gene Shue", "coached", "Philadelphia 76ers", 0.56),
        scoredTriple("Wells Fargo Center", "is_in", "Philadelphia", 0.62),
        scoredTriple("Barclays Center", "home_of", "Brooklyn Nets", 0.58),
      ],
    },
  },
  "giguere-ducks-oilers": {
    id: "giguere-ducks-oilers",
    canonicalQuestion:
      "Which team did the general manager of the club that hired the coach of the team employing the winner of the 2003 Conn Smythe Trophy later run?",
    expectedAnswer: "Edmonton Oilers",
    pathLength: 6,
    hopCount: 6,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2003 Conn Smythe Trophy",
          relationship: "won_by",
          node2: "Jean-Sebastien Giguere",
        },
        {
          node1: "Jean-Sebastien Giguere",
          relationship: "played_for",
          node2: "Anaheim Mighty Ducks",
        },
        {
          node1: "Anaheim Mighty Ducks",
          relationship: "coached_by",
          node2: "Mike Babcock",
        },
        {
          node1: "Mike Babcock",
          relationship: "joined",
          node2: "Detroit Red Wings",
        },
        {
          node1: "Detroit Red Wings",
          relationship: "had_GM",
          node2: "Ken Holland",
        },
        {
          node1: "Ken Holland",
          relationship: "joined",
          node2: "Edmonton Oilers",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2003 Conn Smythe Trophy", "won_by", "Jean-Sebastien Giguere", 1.0),
        scoredTriple("Jean-Sebastien Giguere", "played_for", "Anaheim Mighty Ducks", 1.0),
        scoredTriple("Anaheim Mighty Ducks", "coached_by", "Mike Babcock", 1.0),
        scoredTriple("Mike Babcock", "joined", "Detroit Red Wings", 1.0),
        scoredTriple("Detroit Red Wings", "had_GM", "Ken Holland", 1.0),
        scoredTriple("Ken Holland", "joined", "Edmonton Oilers", 1.0),
        scoredTriple("Ken Holland", "managed", "Detroit Red Wings", 0.88),
        scoredTriple("Ken Holland", "won", "2008 Stanley Cup", 0.76),
        scoredTriple("Ken Holland", "belonged_to", "NHL executives", 0.56),
        scoredTriple("Ken Holland", "preceded", "Steve Yzerman", 0.64),
        scoredTriple("Edmonton Oilers", "belonged_to", "NHL", 0.82),
        scoredTriple("Edmonton Oilers", "used", "Rogers Place", 0.72),
        scoredTriple("Edmonton Oilers", "had_player", "Connor McDavid", 0.8),
        scoredTriple("Edmonton Oilers", "won", "1988 Stanley Cup", 0.68),
        scoredTriple("Jean-Sebastien Giguere", "played_for", "Toronto Maple Leafs", 0.66),
        scoredTriple("Jean-Sebastien Giguere", "played_for", "Colorado Avalanche", 0.62),
        scoredTriple("Jean-Sebastien Giguere", "played_in", "NHL", 0.8),
        scoredTriple("Anaheim Mighty Ducks", "belonged_to", "NHL", 0.84),
        scoredTriple("Anaheim Mighty Ducks", "based_in", "Anaheim", 0.8),
        scoredTriple("Anaheim Mighty Ducks", "used", "Arrowhead Pond", 0.72),
        scoredTriple("Anaheim Mighty Ducks", "played_in", "2003 Stanley Cup Final", 0.78),
        scoredTriple("Anaheim Mighty Ducks", "had_player", "Paul Kariya", 0.74),
        scoredTriple("Mike Babcock", "coached", "Toronto Maple Leafs", 0.72),
        scoredTriple("Mike Babcock", "won", "2008 Stanley Cup", 0.8),
        scoredTriple("Mike Babcock", "belonged_to", "NHL coaches", 0.6),
        scoredTriple("Detroit Red Wings", "belonged_to", "NHL", 0.84),
        scoredTriple("Detroit Red Wings", "based_in", "Detroit", 0.82),
        scoredTriple("Detroit Red Wings", "won", "2008 Stanley Cup", 0.86),
        scoredTriple("Detroit Red Wings", "used", "Joe Louis Arena", 0.7),
        scoredTriple("Detroit Red Wings", "had_player", "Steve Yzerman", 0.76),
        scoredTriple("2003 Stanley Cup Final", "had_finalist", "New Jersey Devils", 0.72),
        scoredTriple("New Jersey Devils", "won", "2003 Stanley Cup", 0.78),
        scoredTriple("Paul Kariya", "played_for", "Anaheim Mighty Ducks", 0.82),
        scoredTriple("Steve Yzerman", "captained", "Detroit Red Wings", 0.74),
        scoredTriple("Steve Yzerman", "succeeded", "Ken Holland", 0.62),
        scoredTriple("Rogers Place", "is_in", "Edmonton", 0.68),
        scoredTriple("Connor McDavid", "won", "Art Ross Trophy", 0.72),
      ],
    },
  },
  "billups-pistons-united-states": {
    id: "billups-pistons-united-states",
    canonicalQuestion:
      "Which country contains the state hosting the arena of the team that employed the winner of the 2004 NBA Finals MVP?",
    expectedAnswer: "United States",
    pathLength: 6,
    hopCount: 6,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2004 NBA Finals MVP",
          relationship: "won_by",
          node2: "Chauncey Billups",
        },
        {
          node1: "Chauncey Billups",
          relationship: "played_for",
          node2: "Detroit Pistons",
        },
        {
          node1: "Detroit Pistons",
          relationship: "used",
          node2: "The Palace of Auburn Hills",
        },
        {
          node1: "The Palace of Auburn Hills",
          relationship: "is_in",
          node2: "Auburn Hills",
        },
        {
          node1: "Auburn Hills",
          relationship: "is_in",
          node2: "Michigan",
        },
        {
          node1: "Michigan",
          relationship: "is_in",
          node2: "United States",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2004 NBA Finals MVP", "won_by", "Chauncey Billups", 1.0),
        scoredTriple("Chauncey Billups", "played_for", "Detroit Pistons", 1.0),
        scoredTriple("Detroit Pistons", "used", "The Palace of Auburn Hills", 1.0),
        scoredTriple("The Palace of Auburn Hills", "is_in", "Auburn Hills", 1.0),
        scoredTriple("Auburn Hills", "is_in", "Michigan", 1.0),
        scoredTriple("Michigan", "is_in", "United States", 1.0),
        scoredTriple("United States", "contains", "Michigan", 0.82),
        scoredTriple("United States", "contains", "Los Angeles", 0.76),
        scoredTriple("United States", "contains", "Denver", 0.7),
        scoredTriple("United States", "is_in", "North America", 0.74),
        scoredTriple("Michigan", "contains", "Detroit", 0.86),
        scoredTriple("Michigan", "contains", "Auburn Hills", 0.82),
        scoredTriple("Michigan", "home_of", "University of Michigan", 0.68),
        scoredTriple("Michigan", "contains", "Lansing", 0.56),
        scoredTriple("Chauncey Billups", "played_for", "Denver Nuggets", 0.74),
        scoredTriple("Chauncey Billups", "played_for", "Minnesota Timberwolves", 0.62),
        scoredTriple("Chauncey Billups", "won", "2004 NBA Championship", 0.88),
        scoredTriple("Chauncey Billups", "played_in", "NBA", 0.82),
        scoredTriple("Chauncey Billups", "studied_at", "University of Colorado", 0.58),
        scoredTriple("Detroit Pistons", "belonged_to", "NBA", 0.86),
        scoredTriple("Detroit Pistons", "won", "2004 NBA Championship", 0.9),
        scoredTriple("Detroit Pistons", "coached_by", "Larry Brown", 0.8),
        scoredTriple("Detroit Pistons", "had_player", "Ben Wallace", 0.76),
        scoredTriple("Detroit Pistons", "had_player", "Richard Hamilton", 0.72),
        scoredTriple("Detroit Pistons", "defeated", "Los Angeles Lakers", 0.84),
        scoredTriple("2004 NBA Championship", "had_finalist", "Los Angeles Lakers", 0.78),
        scoredTriple("Los Angeles Lakers", "belonged_to", "NBA", 0.82),
        scoredTriple("Los Angeles Lakers", "had_player", "Shaquille O'Neal", 0.74),
        scoredTriple("Larry Brown", "coached", "Indiana Pacers", 0.66),
        scoredTriple("Larry Brown", "inducted_into", "Basketball Hall of Fame", 0.6),
        scoredTriple("Ben Wallace", "won", "Defensive Player of the Year", 0.68),
        scoredTriple("Denver Nuggets", "belonged_to", "NBA", 0.7),
        scoredTriple("Denver Nuggets", "based_in", "Denver", 0.72),
        scoredTriple("Detroit", "home_of", "Detroit Pistons", 0.78),
        scoredTriple("Richard Hamilton", "played_for", "Detroit Pistons", 0.7),
        scoredTriple("University of Colorado", "based_in", "Boulder", 0.52),
        scoredTriple("NBA", "includes", "Detroit Pistons", 0.58),
        scoredTriple("Larry Brown", "preceded", "Flip Saunders", 0.52),
      ],
    },
  },
  "bryant-lakers-celtics-massachusetts": {
    id: "bryant-lakers-celtics-massachusetts",
    canonicalQuestion:
      "Which state contains the city hosting the arena used by the team defeated by the franchise of the 2010 NBA Finals MVP?",
    expectedAnswer: "Massachusetts",
    pathLength: 6,
    hopCount: 6,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2010 NBA Finals MVP",
          relationship: "won_by",
          node2: "Kobe Bryant",
        },
        {
          node1: "Kobe Bryant",
          relationship: "played_for",
          node2: "Los Angeles Lakers",
        },
        {
          node1: "Los Angeles Lakers",
          relationship: "defeated",
          node2: "Boston Celtics",
        },
        {
          node1: "Boston Celtics",
          relationship: "used",
          node2: "TD Garden",
        },
        {
          node1: "TD Garden",
          relationship: "is_in",
          node2: "Boston",
        },
        {
          node1: "Boston",
          relationship: "is_in",
          node2: "Massachusetts",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2010 NBA Finals MVP", "won_by", "Kobe Bryant", 1.0),
        scoredTriple("Kobe Bryant", "played_for", "Los Angeles Lakers", 1.0),
        scoredTriple("Los Angeles Lakers", "defeated", "Boston Celtics", 1.0),
        scoredTriple("Boston Celtics", "used", "TD Garden", 1.0),
        scoredTriple("TD Garden", "is_in", "Boston", 1.0),
        scoredTriple("Boston", "is_in", "Massachusetts", 1.0),
        scoredTriple("Massachusetts", "is_in", "United States", 0.82),
        scoredTriple("Massachusetts", "contains", "Boston", 0.78),
        scoredTriple("Massachusetts", "contains", "Cambridge", 0.7),
        scoredTriple("Massachusetts", "produced", "John F. Kennedy", 0.62),
        scoredTriple("Kobe Bryant", "won", "2009 NBA Finals MVP", 0.84),
        scoredTriple("Kobe Bryant", "played_in", "NBA", 0.88),
        scoredTriple("Kobe Bryant", "born_in", "Philadelphia", 0.6),
        scoredTriple("Kobe Bryant", "inducted_into", "Basketball Hall of Fame", 0.72),
        scoredTriple("Los Angeles Lakers", "belonged_to", "NBA", 0.92),
        scoredTriple("Los Angeles Lakers", "coached_by", "Phil Jackson", 0.86),
        scoredTriple("Los Angeles Lakers", "won", "2010 NBA Championship", 0.9),
        scoredTriple("Los Angeles Lakers", "had_player", "Pau Gasol", 0.76),
        scoredTriple("Los Angeles Lakers", "used", "Staples Center", 0.8),
        scoredTriple("Boston Celtics", "belonged_to", "NBA", 0.88),
        scoredTriple("Boston Celtics", "had_player", "Paul Pierce", 0.78),
        scoredTriple("Boston Celtics", "coached_by", "Doc Rivers", 0.74),
        scoredTriple("Boston Celtics", "won", "2008 NBA Championship", 0.8),
        scoredTriple("TD Garden", "home_of", "Boston Bruins", 0.62),
        scoredTriple("TD Garden", "hosts", "NBA", 0.56),
        scoredTriple("Boston", "home_of", "Fenway Park", 0.72),
        scoredTriple("Phil Jackson", "coached", "Chicago Bulls", 0.8),
        scoredTriple("Phil Jackson", "inducted_into", "Basketball Hall of Fame", 0.68),
        scoredTriple("Paul Pierce", "won", "2008 NBA Finals MVP", 0.72),
        scoredTriple("Doc Rivers", "coached", "Los Angeles Clippers", 0.62),
        scoredTriple("Pau Gasol", "played_for", "Memphis Grizzlies", 0.66),
        scoredTriple("Chicago Bulls", "belonged_to", "NBA", 0.72),
        scoredTriple("2010 NBA Championship", "had_finalist", "Boston Celtics", 0.82),
        scoredTriple("Staples Center", "based_in", "Los Angeles", 0.7),
        scoredTriple("Cambridge", "home_of", "Harvard University", 0.6),
      ],
    },
  },
  "messi-barca-khaldoon-abu-dhabi": {
    id: "messi-barca-khaldoon-abu-dhabi",
    canonicalQuestion:
      "In which city was the chairman of the club later coached by the manager who led the 2010 Ballon d'Or winner's club born?",
    expectedAnswer: "Abu Dhabi",
    pathLength: 6,
    hopCount: 6,
    isCorrect: true,
    clauses: {
      clauses: [
        {
          node1: "2010 Ballon d'Or",
          relationship: "won_by",
          node2: "Lionel Messi",
        },
        {
          node1: "Lionel Messi",
          relationship: "played_for",
          node2: "FC Barcelona",
        },
        {
          node1: "FC Barcelona",
          relationship: "managed_by",
          node2: "Pep Guardiola",
        },
        {
          node1: "Pep Guardiola",
          relationship: "joined",
          node2: "Manchester City",
        },
        {
          node1: "Manchester City",
          relationship: "chaired_by",
          node2: "Khaldoon Al Mubarak",
        },
        {
          node1: "Khaldoon Al Mubarak",
          relationship: "born_in",
          node2: "Abu Dhabi",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2010 Ballon d'Or", "won_by", "Lionel Messi", 1.0),
        scoredTriple("Lionel Messi", "played_for", "FC Barcelona", 1.0),
        scoredTriple("FC Barcelona", "managed_by", "Pep Guardiola", 1.0),
        scoredTriple("Pep Guardiola", "joined", "Manchester City", 1.0),
        scoredTriple("Manchester City", "chaired_by", "Khaldoon Al Mubarak", 1.0),
        scoredTriple("Khaldoon Al Mubarak", "born_in", "Abu Dhabi", 1.0),
        scoredTriple("Khaldoon Al Mubarak", "leads", "Mubadala Investment Company", 0.76),
        scoredTriple("Khaldoon Al Mubarak", "belonged_to", "Emirati executives", 0.62),
        scoredTriple("Khaldoon Al Mubarak", "studied_at", "Tufts University", 0.56),
        scoredTriple("Khaldoon Al Mubarak", "leads", "Executive Affairs Authority", 0.6),
        scoredTriple("Lionel Messi", "won", "2009 Ballon d'Or", 0.84),
        scoredTriple("Lionel Messi", "played_for", "Argentina national football team", 0.82),
        scoredTriple("Lionel Messi", "born_in", "Rosario", 0.64),
        scoredTriple("Lionel Messi", "played_in", "La Liga", 0.8),
        scoredTriple("Lionel Messi", "joined", "Paris Saint-Germain", 0.7),
        scoredTriple("FC Barcelona", "played_in", "La Liga", 0.9),
        scoredTriple("FC Barcelona", "used", "Camp Nou", 0.84),
        scoredTriple("FC Barcelona", "won", "2011 Champions League", 0.82),
        scoredTriple("FC Barcelona", "based_in", "Barcelona", 0.88),
        scoredTriple("Pep Guardiola", "managed", "Bayern Munich", 0.78),
        scoredTriple("Pep Guardiola", "played_for", "FC Barcelona", 0.76),
        scoredTriple("Pep Guardiola", "won", "2011 Champions League", 0.8),
        scoredTriple("Pep Guardiola", "born_in", "Santpedor", 0.54),
        scoredTriple("Manchester City", "plays_in", "Premier League", 0.92),
        scoredTriple("Manchester City", "won", "2012 Premier League", 0.8),
        scoredTriple("Manchester City", "used", "Etihad Stadium", 0.78),
        scoredTriple("Manchester City", "had_player", "Sergio Aguero", 0.76),
        scoredTriple("Manchester City", "based_in", "Manchester", 0.7),
        scoredTriple("Abu Dhabi", "home_of", "Mubadala Investment Company", 0.72),
        scoredTriple("Abu Dhabi", "produced", "Sheikh Mansour", 0.68),
        scoredTriple("Abu Dhabi", "home_of", "City Football Group", 0.6),
        scoredTriple("Abu Dhabi", "is_in", "United Arab Emirates", 0.78),
        scoredTriple("Sheikh Mansour", "owns", "City Football Group", 0.74),
        scoredTriple("City Football Group", "owns", "Manchester City", 0.68),
        scoredTriple("Bayern Munich", "plays_in", "Bundesliga", 0.7),
        scoredTriple("Sergio Aguero", "won", "2012 Premier League", 0.64),
        scoredTriple("Etihad Stadium", "is_in", "Manchester", 0.62),
      ],
    },
  },
  "kalou-chelsea-toennies-group": {
    id: "kalou-chelsea-toennies-group",
    canonicalQuestion:
      "Which company is associated with the chairman of the club later managed by the coach who led the team that employed Salomon Kalou during their 2012 Champions League victory?",
    expectedAnswer: "Toennies Group",
    pathLength: 6,
    hopCount: 6,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "Salomon Kalou",
          relationship: "played_for",
          node2: "Chelsea",
        },
        {
          node1: "Chelsea",
          relationship: "managed_by",
          node2: "Roberto Di Matteo",
        },
        {
          node1: "Roberto Di Matteo",
          relationship: "managed",
          node2: "VfB Stuttgart",
        },
        {
          node1: "VfB Stuttgart",
          relationship: "is_in",
          node2: "Baden-Wurttemberg",
        },
        {
          node1: "VfB Stuttgart",
          relationship: "chaired_by",
          node2: "Clemens Toennies",
        },
        {
          node1: "Clemens Toennies",
          relationship: "owns",
          node2: "Toennies Group",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("Salomon Kalou", "played_for", "Chelsea", 1.0),
        scoredTriple("Chelsea", "managed_by", "Roberto Di Matteo", 1.0),
        scoredTriple("Roberto Di Matteo", "managed", "VfB Stuttgart", 1.0),
        scoredTriple("VfB Stuttgart", "is_in", "Baden-Wurttemberg", 1.0),
        scoredTriple("Clemens Toennies", "owns", "Toennies Group", 1.0),
        scoredTriple("Clemens Toennies", "chaired", "Schalke 04", 0.88),
        scoredTriple("Clemens Toennies", "born_in", "Rheda-Wiedenbruck", 0.52),
        scoredTriple("Clemens Toennies", "active_in", "Bundesliga", 0.58),
        scoredTriple("Clemens Toennies", "succeeded", "Gerhard Rehberg", 0.48),
        scoredTriple("Toennies Group", "founded_by", "Clemens Toennies", 0.74),
        scoredTriple("Toennies Group", "owns", "Toennies Lebensmittel", 0.66),
        scoredTriple("Toennies Group", "part_of", "German meat industry", 0.58),
        scoredTriple("Toennies Group", "founded", "Rheda processing plant", 0.52),
        scoredTriple("Salomon Kalou", "played_for", "Hertha Berlin", 0.72),
        scoredTriple("Salomon Kalou", "played_for", "Ivory Coast national team", 0.8),
        scoredTriple("Salomon Kalou", "played_in", "Premier League", 0.76),
        scoredTriple("Salomon Kalou", "born_in", "Oume", 0.5),
        scoredTriple("Chelsea", "won", "2012 Champions League", 0.92),
        scoredTriple("Chelsea", "based_in", "London", 0.86),
        scoredTriple("Chelsea", "plays_in", "Premier League", 0.88),
        scoredTriple("Chelsea", "used", "Stamford Bridge", 0.82),
        scoredTriple("Chelsea", "had_player", "Didier Drogba", 0.78),
        scoredTriple("Roberto Di Matteo", "managed", "Schalke 04", 0.76),
        scoredTriple("Roberto Di Matteo", "managed", "West Bromwich Albion", 0.68),
        scoredTriple("Roberto Di Matteo", "played_for", "Chelsea", 0.72),
        scoredTriple("Roberto Di Matteo", "won", "2012 Champions League", 0.84),
        scoredTriple("Schalke 04", "plays_in", "Bundesliga", 0.82),
        scoredTriple("Schalke 04", "based_in", "Gelsenkirchen", 0.78),
        scoredTriple("Schalke 04", "used", "Veltins-Arena", 0.7),
        scoredTriple("VfB Stuttgart", "plays_in", "Bundesliga", 0.8),
        scoredTriple("VfB Stuttgart", "based_in", "Stuttgart", 0.82),
        scoredTriple("Didier Drogba", "won", "2012 Champions League", 0.8),
        scoredTriple("Hertha Berlin", "plays_in", "Bundesliga", 0.64),
        scoredTriple("Ivory Coast national team", "had_player", "Didier Drogba", 0.66),
        scoredTriple("West Bromwich Albion", "plays_in", "Premier League", 0.6),
        scoredTriple("Bundesliga", "includes", "Schalke 04", 0.56),
        scoredTriple("Roberto Di Matteo", "preceded", "Rafael Benitez", 0.54),
        scoredTriple("Toennies Lebensmittel", "is_in", "Rheda-Wiedenbruck", 0.48),
      ],
    },
  },
  "barrichello-brawn-zetsche-daimler": {
    id: "barrichello-brawn-zetsche-daimler",
    canonicalQuestion:
      "Which company was led by the CEO of the parent company of the constructor whose team principal employed the winner of the 2009 Formula One World Championship?",
    expectedAnswer: "Daimler AG",
    pathLength: 6,
    hopCount: 6,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "2009 Formula One World Championship",
          relationship: "won_by",
          node2: "Rubens Barrichello",
        },
        {
          node1: "Rubens Barrichello",
          relationship: "drove_for",
          node2: "Brawn GP",
        },
        {
          node1: "Brawn GP",
          relationship: "led_by",
          node2: "Ross Brawn",
        },
        {
          node1: "Ross Brawn",
          relationship: "joined",
          node2: "Mercedes-Benz",
        },
        {
          node1: "Mercedes-Benz",
          relationship: "led_by",
          node2: "Dieter Zetsche",
        },
        {
          node1: "Dieter Zetsche",
          relationship: "led",
          node2: "Daimler AG",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2009 Formula One World Championship", "won_by", "Jenson Button", 1.0),
        scoredTriple("Rubens Barrichello", "drove_for", "Brawn GP", 1.0),
        scoredTriple("Brawn GP", "led_by", "Ross Brawn", 1.0),
        scoredTriple("Ross Brawn", "joined", "Mercedes-Benz", 1.0),
        scoredTriple("Dieter Zetsche", "led", "Daimler AG", 1.0),
        scoredTriple("Dieter Zetsche", "succeeded", "Juergen Schrempp", 0.64),
        scoredTriple("Dieter Zetsche", "preceded", "Ola Kaellenius", 0.6),
        scoredTriple("Dieter Zetsche", "born_in", "Istanbul", 0.5),
        scoredTriple("Dieter Zetsche", "studied_at", "Karlsruhe Institute of Technology", 0.54),
        scoredTriple("Dieter Zetsche", "belonged_to", "German industrialists", 0.48),
        scoredTriple("Jenson Button", "drove_for", "Brawn GP", 0.88),
        scoredTriple("Jenson Button", "drove_for", "McLaren", 0.76),
        scoredTriple("Jenson Button", "born_in", "Frome", 0.52),
        scoredTriple("Rubens Barrichello", "drove_for", "Ferrari", 0.84),
        scoredTriple("Rubens Barrichello", "drove_for", "Williams", 0.62),
        scoredTriple("Rubens Barrichello", "born_in", "Sao Paulo", 0.58),
        scoredTriple("Rubens Barrichello", "set", "Most F1 race starts record", 0.64),
        scoredTriple("Brawn GP", "won", "2009 Constructors Championship", 0.88),
        scoredTriple("Brawn GP", "succeeded", "Honda Racing", 0.8),
        scoredTriple("Brawn GP", "based_in", "Brackley", 0.7),
        scoredTriple("Brawn GP", "competed_in", "Formula One", 0.82),
        scoredTriple("Brawn GP", "had_driver", "Jenson Button", 0.84),
        scoredTriple("Ross Brawn", "led", "Mercedes F1", 0.82),
        scoredTriple("Ross Brawn", "led", "Ferrari", 0.78),
        scoredTriple("Ross Brawn", "worked_in", "Formula One", 0.68),
        scoredTriple("Daimler AG", "owns", "Mercedes-Benz", 0.86),
        scoredTriple("Daimler AG", "owns", "Mercedes F1", 0.72),
        scoredTriple("Daimler AG", "founded", "AMG", 0.66),
        scoredTriple("Daimler AG", "part_of", "German automotive industry", 0.6),
        scoredTriple("Mercedes F1", "succeeded", "Brawn GP", 0.82),
        scoredTriple("Mercedes F1", "competed_in", "Formula One", 0.76),
        scoredTriple("Ferrari", "competed_in", "Formula One", 0.84),
        scoredTriple("Ferrari", "based_in", "Maranello", 0.8),
        scoredTriple("Honda Racing", "competed_in", "Formula One", 0.64),
        scoredTriple("Sao Paulo", "home_of", "Interlagos", 0.56),
        scoredTriple("AMG", "owned_by", "Daimler AG", 0.58),
      ],
    },
  },
  "curry-warriors-popovich-east-chicago": {
    id: "curry-warriors-popovich-east-chicago",
    canonicalQuestion:
      "In which Indiana city was the head coach of the former team of the coach who led the team of the winner of the 2015 NBA Finals MVP born?",
    expectedAnswer: "East Chicago",
    pathLength: 6,
    hopCount: 6,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "2015 NBA Finals MVP",
          relationship: "won_by",
          node2: "Stephen Curry",
        },
        {
          node1: "Stephen Curry",
          relationship: "played_for",
          node2: "Golden State Warriors",
        },
        {
          node1: "Golden State Warriors",
          relationship: "coached_by",
          node2: "Steve Kerr",
        },
        {
          node1: "Steve Kerr",
          relationship: "played_for",
          node2: "San Antonio Spurs",
        },
        {
          node1: "San Antonio Spurs",
          relationship: "coached_by",
          node2: "Gregg Popovich",
        },
        {
          node1: "Gregg Popovich",
          relationship: "born_in",
          node2: "East Chicago",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2015 NBA Finals MVP", "won_by", "Andre Iguodala", 1.0),
        scoredTriple("Stephen Curry", "played_for", "Golden State Warriors", 1.0),
        scoredTriple("Golden State Warriors", "coached_by", "Steve Kerr", 1.0),
        scoredTriple("San Antonio Spurs", "coached_by", "Gregg Popovich", 1.0),
        scoredTriple("Gregg Popovich", "born_in", "East Chicago", 1.0),
        scoredTriple("Gregg Popovich", "won", "2014 NBA Championship", 0.82),
        scoredTriple("Gregg Popovich", "belonged_to", "NBA coaches", 0.68),
        scoredTriple("Gregg Popovich", "coached", "United States national basketball team", 0.6),
        scoredTriple("Gregg Popovich", "studied_at", "Air Force Academy", 0.56),
        scoredTriple("Stephen Curry", "won", "2015 NBA MVP", 0.82),
        scoredTriple("Stephen Curry", "played_in", "NBA", 0.88),
        scoredTriple("Stephen Curry", "studied_at", "Davidson College", 0.6),
        scoredTriple("Stephen Curry", "won", "2015 NBA Championship", 0.86),
        scoredTriple("Andre Iguodala", "played_for", "Golden State Warriors", 0.84),
        scoredTriple("Andre Iguodala", "won", "2015 NBA Championship", 0.8),
        scoredTriple("Andre Iguodala", "played_for", "Philadelphia 76ers", 0.64),
        scoredTriple("Golden State Warriors", "belonged_to", "NBA", 0.9),
        scoredTriple("Golden State Warriors", "based_in", "Oakland", 0.78),
        scoredTriple("Golden State Warriors", "used", "Oracle Arena", 0.76),
        scoredTriple("Golden State Warriors", "won", "2015 NBA Championship", 0.88),
        scoredTriple("Golden State Warriors", "had_player", "Klay Thompson", 0.76),
        scoredTriple("Steve Kerr", "won", "1996 NBA Championship", 0.74),
        scoredTriple("Steve Kerr", "played_for", "Chicago Bulls", 0.78),
        scoredTriple("Steve Kerr", "played_in", "NBA", 0.78),
        scoredTriple("San Antonio Spurs", "belonged_to", "NBA", 0.86),
        scoredTriple("San Antonio Spurs", "won", "1999 NBA Championship", 0.8),
        scoredTriple("San Antonio Spurs", "used", "AT&T Center", 0.7),
        scoredTriple("San Antonio Spurs", "had_player", "Tim Duncan", 0.84),
        scoredTriple("East Chicago", "contains", "Indiana Harbor", 0.6),
        scoredTriple("East Chicago", "produced", "Gregg Popovich", 0.7),
        scoredTriple("East Chicago", "is_in", "Lake County", 0.58),
        scoredTriple("East Chicago", "is_in", "Indiana", 0.64),
        scoredTriple("Tim Duncan", "won", "1999 NBA Finals MVP", 0.76),
        scoredTriple("2015 NBA Championship", "had_finalist", "Cleveland Cavaliers", 0.78),
        scoredTriple("Cleveland Cavaliers", "belonged_to", "NBA", 0.7),
        scoredTriple("Klay Thompson", "won", "2015 NBA Championship", 0.68),
      ],
    },
  },
  "cannavaro-juventus-perez-madrid": {
    id: "cannavaro-juventus-perez-madrid",
    canonicalQuestion:
      "In which city was the president of the club coached by the manager of the Italian club that employed the player awarded the 2006 FIFA World Cup Golden Ball born?",
    expectedAnswer: "Madrid",
    pathLength: 6,
    hopCount: 6,
    isCorrect: false,
    clauses: {
      clauses: [
        {
          node1: "2006 FIFA World Cup Golden Ball",
          relationship: "won_by",
          node2: "Fabio Cannavaro",
        },
        {
          node1: "Fabio Cannavaro",
          relationship: "played_for",
          node2: "Juventus",
        },
        {
          node1: "Juventus",
          relationship: "managed_by",
          node2: "Fabio Capello",
        },
        {
          node1: "Fabio Capello",
          relationship: "managed",
          node2: "Real Madrid",
        },
        {
          node1: "Real Madrid",
          relationship: "presided_by",
          node2: "Florentino Perez",
        },
        {
          node1: "Florentino Perez",
          relationship: "born_in",
          node2: "Madrid",
        },
      ],
    },
    graph: {
      triples: [
        scoredTriple("2006 FIFA World Cup Golden Ball", "won_by", "Zinedine Zidane", 1.0),
        scoredTriple("Fabio Cannavaro", "played_for", "Juventus", 1.0),
        scoredTriple("Fabio Capello", "managed", "Real Madrid", 1.0),
        scoredTriple("Florentino Perez", "born_in", "Madrid", 1.0),
        scoredTriple("Florentino Perez", "leads", "ACS Group", 0.74),
        scoredTriple("Florentino Perez", "succeeded", "Lorenzo Sanz", 0.66),
        scoredTriple("Florentino Perez", "belonged_to", "Spanish businessmen", 0.58),
        scoredTriple("Florentino Perez", "studied_at", "Technical University of Madrid", 0.54),
        scoredTriple("Fabio Cannavaro", "won", "2006 FIFA World Cup", 0.82),
        scoredTriple("Fabio Cannavaro", "played_for", "Real Madrid", 0.74),
        scoredTriple("Fabio Cannavaro", "played_for", "Italy national football team", 0.84),
        scoredTriple("Fabio Cannavaro", "won", "2006 Ballon d'Or", 0.78),
        scoredTriple("Zinedine Zidane", "played_for", "Real Madrid", 0.86),
        scoredTriple("Zinedine Zidane", "won", "1998 FIFA World Cup", 0.78),
        scoredTriple("Zinedine Zidane", "coached", "Real Madrid", 0.72),
        scoredTriple("Juventus", "plays_in", "Serie A", 0.88),
        scoredTriple("Juventus", "based_in", "Turin", 0.82),
        scoredTriple("Juventus", "used", "Juventus Stadium", 0.72),
        scoredTriple("Juventus", "had_player", "Alessandro Del Piero", 0.76),
        scoredTriple("Fabio Capello", "managed", "AC Milan", 0.76),
        scoredTriple("Fabio Capello", "managed", "Juventus", 0.74),
        scoredTriple("Fabio Capello", "managed", "England national football team", 0.66),
        scoredTriple("Fabio Capello", "won", "2006-07 La Liga", 0.72),
        scoredTriple("Real Madrid", "plays_in", "La Liga", 0.9),
        scoredTriple("Real Madrid", "used", "Santiago Bernabeu", 0.84),
        scoredTriple("Real Madrid", "won", "2002 Champions League", 0.8),
        scoredTriple("Real Madrid", "had_player", "Cristiano Ronaldo", 0.82),
        scoredTriple("Madrid", "is_in", "Spain", 0.84),
        scoredTriple("Madrid", "home_of", "Santiago Bernabeu", 0.72),
        scoredTriple("Madrid", "produced", "Florentino Perez", 0.66),
        scoredTriple("Madrid", "home_of", "Real Madrid", 0.6),
        scoredTriple("Alessandro Del Piero", "won", "2006 FIFA World Cup", 0.7),
        scoredTriple("Cristiano Ronaldo", "won", "2013 Ballon d'Or", 0.72),
        scoredTriple("ACS Group", "part_of", "Spanish conglomerates", 0.56),
      ],
    },
  },
};

export const STUDY_QUESTION_FIXTURES: Record<
  StudyQuestionId,
  StudyQuestionFixture
> = Object.fromEntries(
  STUDY_QUESTION_IDS.map((id) => [
    id,
    { ...STUDY_QUESTION_FIXTURES_RAW[id], studyNumber: STUDY_QUESTION_NUMBERS[id] },
  ])
) as Record<StudyQuestionId, StudyQuestionFixture>;

export const STUDY_QUESTION_NUMBER_BY_TEXT: Record<string, string> =
  Object.fromEntries(
    STUDY_QUESTION_IDS.map((id) => [
      STUDY_QUESTION_FIXTURES_RAW[id].canonicalQuestion,
      STUDY_QUESTION_NUMBERS[id],
    ])
  );

export function lookupStudyNumberByText(text: string): string | undefined {
  return STUDY_QUESTION_NUMBER_BY_TEXT[text.trim()];
}

export function getStudyFixtureByNumber(
  value: string | number
): StudyQuestionFixture | undefined {
  const num =
    typeof value === "number" ? value : Number.parseInt(value, 10);
  if (!Number.isInteger(num) || num < 1 || num > STUDY_QUESTION_IDS.length) {
    return undefined;
  }
  const id = STUDY_QUESTION_IDS[num - 1];
  return STUDY_QUESTION_FIXTURES[id];
}
